### ISSUE TITLE
NPM Package name

### ISSUE THREAD

**Issue by boopathi** [jtmthf/babel-plugin-graphql-tag#1]
Regarding https://github.com/apollographql/graphql-tag/issues/31 

I started working on this sometime back and I'm not working on it anymore. I can add you as the owner of the package `babel-plugin-graphql-tag` on npm. I need your npm handle.

Thanks for working on this.

**Comment by jtmthf** [comment]
Thank you! My handle is the same as github, jtmthf

**Comment by boopathi** [comment]
Done 👍
